/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, cleanupOutdatedCaches, matchPrecache } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst } from 'workbox-strategies';

declare const self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite EXCEPT index.html
const manifest = (self.__WB_MANIFEST as any[]).filter(
  (entry) => {
    const url = typeof entry === 'string' ? entry : entry.url;
    return !url.includes('index.html');
  }
);
precacheAndRoute(manifest);

// Always fetch index.html from network (never cache)
registerRoute(
  new NavigationRoute(
    new NetworkFirst({
      cacheName: 'html-cache',
      networkTimeoutSeconds: 3,
    })
  )
);

// Cleanup old caches
cleanupOutdatedCaches();

// Take control of all clients immediately
clientsClaim();

// Skip waiting and activate immediately
self.skipWaiting();

// Cache strategies for runtime requests
registerRoute(
  ({ url }) => url.pathname.startsWith('/assets/'),
  new NetworkFirst({
    cacheName: 'assets-cache',
  })
);

registerRoute(
  ({ url, request }) => {
    // CRITICAL: Explicitly bypass SSE stream and WebSockets from Workbox interception
    const isSSE = url.pathname.includes('/notifications/stream') || 
                  url.href.includes('/notifications/stream') ||
                  url.pathname.includes('/sse') ||
                  url.pathname.includes('/stream');
                  
    const isEventStream = request.headers.get('Accept') === 'text/event-stream';
    const isNoCache = request.headers.get('Cache-Control')?.includes('no-cache') || 
                     request.headers.get('Pragma') === 'no-cache';
    
    // Also bypass if it's a cross-origin request to the API port which might be a stream
    const isApiPort = url.port === '5000' || url.port === '5001' || url.port === '3000';

    if (isSSE || isEventStream || isNoCache || (isApiPort && url.pathname.includes('/api/'))) {
        // If it's a stream or SSE, definitely bypass
        if (isSSE || isEventStream) {
            console.log('[SW] 🚀 BYPASSING Workbox for Realtime/Stream:', url.href);
            return false;
        }
        
        // If it's a regular API call but we want to be safe, we can still return false here
        // to let the browser handle it directly if we suspect it's a long-lived connection
        if (url.pathname.includes('/realtime') || url.pathname.includes('/ws')) {
            console.log('[SW] 🚀 BYPASSING Workbox for Realtime API:', url.href);
            return false;
        }
    }

    // Cache other API requests with NetworkFirst
    return url.pathname.startsWith('/api/') || url.href.includes(':5000/api/');
  },
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      {
        cacheWillUpdate: async ({ response }) => {
          // Extra safety: never cache event-stream responses even if logic above fails
          if (response.headers.get('content-type')?.includes('text/event-stream')) {
            return null;
          }
          return response;
        }
      }
    ]
  })
);

// Push notification handler
self.addEventListener('push', (event: PushEvent) => {
  console.log('[SW] Push event received!', event);

  if (!event.data) {
    console.warn('[SW] Push event has no data');
    return;
  }

  try {
    const data = event.data.json();
    console.log('[SW] Push data:', data);

    const options: any = {
      body: data.body || '',
      icon: data.icon || '/pwa-192x192.png',
      badge: data.badge || '/pwa-192x192.png',
      vibrate: [200, 100, 200],
      data: {
        url: data.url || '/',
        timestamp: Date.now(),
      },
      actions: data.actions || [
        { action: 'open', title: 'Открыть' },
      ],
      requireInteraction: false,
      silent: false,
      tag: data.tag || 'notification',
    };

    event.waitUntil(
      Promise.all([
        // Show notification
        self.registration.showNotification(data.title || 'Уведомление', options).then(() => {
          console.log('[SW] Notification shown successfully');
        }).catch((err) => {
          console.error('[SW] Failed to show notification:', err);
        }),
        // Play sound by sending message to all clients
        self.clients.matchAll({ includeUncontrolled: true, type: 'window' }).then((clients) => {
          console.log('[SW] Found', clients.length, 'clients to notify');
          clients.forEach((client) => {
            client.postMessage({
              type: 'PLAY_NOTIFICATION_SOUND',
              notification: data,
            });
          });
        }),
      ])
    );
  } catch (error) {
    console.error('[SW] Push event error:', error);
  }
});

// Notification click handler
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  event.notification.close();

  const urlToOpen = event.notification.data?.url || '/';

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // Focus existing window if available
      for (const client of clientList) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          return client.focus().then(() => client.navigate(urlToOpen));
        }
      }
      // Open new window
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});
